 {{config(materialized = "table")}} 


WITH INSTALLS AS (
    SELECT *
    FROM {{ ref('v_stg_adjust__installs') }}
    {% if is_incremental() %}
    WHERE INSTALL_TIMESTAMP >= (SELECT MAX(INSTALL_DATE) FROM {{ this }})
    {% endif %}
)

, DEVICE_MAPPING AS (
    SELECT *
    FROM {{ ref('int_adjust_amplitude__device_mapping') }}
)

, AMPLITUDE_EVENTS AS (
    SELECT *
    FROM {{ ref('v_stg_amplitude__events') }}
    {% if is_incremental() %}
    WHERE EVENT_TIME >= (SELECT MAX(INSTALL_DATE) FROM {{ this }})
    {% endif %}
)

, REVENUE_SUMMARY AS (
    SELECT *
    FROM {{ ref('int_revenue__user_summary') }}
)

, BASE_INSTALLS AS (
    SELECT AI.NETWORK_NAME
         , AI.CAMPAIGN_NAME
         , AI.ADGROUP_NAME
         , CAST(AI.INSTALL_TIMESTAMP AS DATE) AS INSTALL_DATE
         , AI.IDFV
         , M.AMPLITUDE_USER_ID
    FROM INSTALLS AI
    LEFT JOIN DEVICE_MAPPING M ON AI.IDFV = M.ADJUST_IDFV
)

, REVENUE_ATTRIBUTED AS (
    SELECT BI.NETWORK_NAME
         , BI.CAMPAIGN_NAME
         , BI.ADGROUP_NAME
         , BI.INSTALL_DATE
         , COUNT(DISTINCT RS.USER_ID) AS PURCHASERS
         , SUM(RS.PURCHASE_COUNT) AS PURCHASE_EVENTS
         , SUM(RS.TOTAL_REVENUE) AS REVENUE
    FROM BASE_INSTALLS BI
    INNER JOIN REVENUE_SUMMARY RS 
      ON BI.AMPLITUDE_USER_ID = RS.USER_ID
    GROUP BY BI.NETWORK_NAME, BI.CAMPAIGN_NAME, BI.ADGROUP_NAME, BI.INSTALL_DATE
)

, LEVEL_UP_ATTRIBUTED AS (
    SELECT BI.NETWORK_NAME
         , BI.CAMPAIGN_NAME
         , BI.ADGROUP_NAME
         , BI.INSTALL_DATE
         , COUNT(DISTINCT AE.USER_ID) AS USERS_LEVELED_UP
         , COUNT(*) AS LEVEL_UP_EVENTS
         , SUM(PARSE_JSON(AE.EVENT_PROPERTIES):v::INTEGER) AS LEVEL_UP_COINS_REWARDED
    FROM BASE_INSTALLS BI
    INNER JOIN AMPLITUDE_EVENTS AE 
      ON BI.AMPLITUDE_USER_ID = AE.USER_ID
      AND AE.EVENT_TIME >= BI.INSTALL_DATE
      AND AE.EVENT_TYPE = 'LevelUpCoinsRewarded'
    GROUP BY BI.NETWORK_NAME, BI.CAMPAIGN_NAME, BI.ADGROUP_NAME, BI.INSTALL_DATE
)

, INSTALL_SUMMARY AS (
    SELECT NETWORK_NAME
         , CAMPAIGN_NAME
         , ADGROUP_NAME
         , INSTALL_DATE
         , COUNT(DISTINCT IDFV) AS INSTALLS
         , COUNT(DISTINCT AMPLITUDE_USER_ID) AS MATCHED_DEVICES
    FROM BASE_INSTALLS
    GROUP BY NETWORK_NAME, CAMPAIGN_NAME, ADGROUP_NAME, INSTALL_DATE
)

SELECT IS_TABLE.NETWORK_NAME
     , IS_TABLE.CAMPAIGN_NAME
     , IS_TABLE.ADGROUP_NAME
     , IS_TABLE.INSTALL_DATE
     , IS_TABLE.INSTALLS
     , IS_TABLE.MATCHED_DEVICES
     , COALESCE(RA.PURCHASERS, 0) AS PURCHASERS
     , COALESCE(RA.PURCHASE_EVENTS, 0) AS PURCHASE_EVENTS
     , COALESCE(RA.REVENUE, 0) AS REVENUE
     , COALESCE(LA.USERS_LEVELED_UP, 0) AS USERS_LEVELED_UP
     , COALESCE(LA.LEVEL_UP_EVENTS, 0) AS LEVEL_UP_EVENTS
     , COALESCE(LA.LEVEL_UP_COINS_REWARDED, 0) AS LEVEL_UP_COINS_REWARDED
FROM INSTALL_SUMMARY IS_TABLE
LEFT JOIN REVENUE_ATTRIBUTED RA 
  ON COALESCE(IS_TABLE.NETWORK_NAME, '') = COALESCE(RA.NETWORK_NAME, '')
  AND COALESCE(IS_TABLE.CAMPAIGN_NAME, '') = COALESCE(RA.CAMPAIGN_NAME, '')
  AND COALESCE(IS_TABLE.ADGROUP_NAME, '') = COALESCE(RA.ADGROUP_NAME, '')
  AND IS_TABLE.INSTALL_DATE = RA.INSTALL_DATE
LEFT JOIN LEVEL_UP_ATTRIBUTED LA 
  ON COALESCE(IS_TABLE.NETWORK_NAME, '') = COALESCE(LA.NETWORK_NAME, '')
  AND COALESCE(IS_TABLE.CAMPAIGN_NAME, '') = COALESCE(LA.CAMPAIGN_NAME, '')
  AND COALESCE(IS_TABLE.ADGROUP_NAME, '') = COALESCE(LA.ADGROUP_NAME, '')
  AND IS_TABLE.INSTALL_DATE = LA.INSTALL_DATE