WITH all_actions AS (
    SELECT DATE
         , AD_ID
         , ACTION_TYPE
    FROM FIVETRAN_DATABASE.FACEBOOK_ADS.ADS_INSIGHTS_ACTIONS
    
    UNION
    
    SELECT DATE
         , AD_ID
         , ACTION_TYPE
    FROM FIVETRAN_DATABASE.FACEBOOK_ADS.ADS_INSIGHTS_CONVERSIONS
)

SELECT DATE
     , AD_ID
     , COUNT(DISTINCT ACTION_TYPE) AS CNT
FROM all_actions
GROUP BY DATE
     , AD_ID
