WITH SOURCE AS (
    SELECT *
    FROM {{ source('adjust', 'IOS_ACTIVITY_INSTALL') }}
)

, CLEANED AS (
    SELECT IDFV
         , NETWORK_NAME
         , CAMPAIGN_NAME
         , ADGROUP_NAME
         , CREATIVE_NAME
         , TRACKER_NAME
         , COUNTRY
         , TO_TIMESTAMP(INSTALLED_AT) AS INSTALL_TIMESTAMP
         , TO_TIMESTAMP(CREATED_AT) AS CREATED_TIMESTAMP
    FROM SOURCE
    WHERE IDFV IS NOT NULL
      AND INSTALLED_AT IS NOT NULL
)

, DEDUPED AS (
    SELECT *
    FROM CLEANED
    QUALIFY ROW_NUMBER() OVER (PARTITION BY IDFV ORDER BY INSTALL_TIMESTAMP ASC) = 1
)

SELECT *
FROM DEDUPED