SELECT USER_ID
     , EVENT_TYPE
     , EVENT_TIME
     , EVENT_PROPERTIES:"$revenue"::DOUBLE AS REVENUE_AMOUNT
     , PLATFORM
     , COUNTRY
FROM {{ source('revenue', 'DIRECT_REVENUE_EVENTS') }}
WHERE EVENT_TIME >= '2025-01-01'